/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.yeisonvargas.battleship.gui;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;

/**
 *
 * @author yeison_vargas
 */
public class Battleship extends javax.swing.JFrame {

    /**
     * Creates new form Battleship
     */
    public Battleship(int level, String name, String photo) {
        initComponents();

        int easy = 9;
        int medium = 13;
        int hard = 19;

        switch (level){
            case 1:
                level = easy;
                break;
            case 2:
                level = medium;
                break;
            case 3:
                level = hard;
                break;
            default:
                break;
        }

        final int height = this.jPanelOwnOcean.getPreferredSize().height / level + 1;
        final int width = this.jPanelOwnOcean.getPreferredSize().width / level + 1;

        /*
        this.load(level, height, width, this.jPanelOwnOcean);
        height = this.jPanelEnemyOcean.getPreferredSize().height / level;
        width = this.jPanelEnemyOcean.getPreferredSize().width / level;
        */

        load(level, height, width, jPanelOwnOcean);
        load(level, height, width, jPanelEnemyOcean);

    }

    public Battleship(String name, String photo) {

    }
    
    private void load(int level, int height, int width, JPanel oceanContainer) {
        final String alphabet [] = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "Ñ", "O", "P",
                "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"};
        oceanContainer.setLayout(new GridLayout(level + 1, level + 1));
        
        JLabel [] [] ocean = new JLabel[level + 1][level + 1];

        for(int x=0; x<ocean.length; x++) {
            for(int y=0; y<ocean[x].length; y++) {
                ocean[x][y] = new JLabel(new ImageIcon(getClass().getResource("sea.jpg")));
                ocean[x][y].setOpaque(true);
                ocean[x][y].setBounds(new Rectangle(width, height));
                oceanContainer.add(ocean[x][y]);
                ocean[x][y].setVisible(true);
                ocean[x][y].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        System.out.println("Yay you clicked me");
                    }
                });
                final int a = x;
                final int b = y;
                ocean[x][y].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseEntered(MouseEvent e) {
                        jLabelPosition.setText(a + 1 + "" + alphabet[b]);
                    }
                });
            }
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpanelBackground = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelOwnOcean = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaChat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNewMessage = new javax.swing.JTextArea();
        jButtonSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonAddShip = new javax.swing.JButton();
        jPanelEnemyOcean = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButtonAddShip1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JpanelBackground.setBackground(java.awt.Color.white);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanelOwnOcean.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanelOwnOcean.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanelOwnOceanLayout = new javax.swing.GroupLayout(jPanelOwnOcean);
        jPanelOwnOcean.setLayout(jPanelOwnOceanLayout);
        jPanelOwnOceanLayout.setHorizontalGroup(
            jPanelOwnOceanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanelOwnOceanLayout.setVerticalGroup(
            jPanelOwnOceanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTextAreaChat.setEditable(false);
        jTextAreaChat.setColumns(20);
        jTextAreaChat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaChat);

        jTextAreaNewMessage.setColumns(20);
        jTextAreaNewMessage.setRows(5);
        jScrollPane2.setViewportView(jTextAreaNewMessage);

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chat");

        jLabel2.setText("Mar Propio");

        jLabel3.setText("Mar Enemigo");

        jTextField1.setText("1A-1B");
        jTextField1.setToolTipText("");

        jButtonAddShip.setText("Agregar Barco");
        jButtonAddShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddShipActionPerformed(evt);
            }
        });

        jPanelEnemyOcean.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanelEnemyOcean.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanelEnemyOceanLayout = new javax.swing.GroupLayout(jPanelEnemyOcean);
        jPanelEnemyOcean.setLayout(jPanelEnemyOceanLayout);
        jPanelEnemyOceanLayout.setHorizontalGroup(
            jPanelEnemyOceanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanelEnemyOceanLayout.setVerticalGroup(
            jPanelEnemyOceanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jLabel4.setText("Posición actual:");

        jLabelPosition.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabelPosition.setForeground(java.awt.Color.red);

        jTextField2.setText("1A");
        jTextField2.setToolTipText("");

        jButtonAddShip1.setText("Atacar");

        javax.swing.GroupLayout JpanelBackgroundLayout = new javax.swing.GroupLayout(JpanelBackground);
        JpanelBackground.setLayout(JpanelBackgroundLayout);
        JpanelBackgroundLayout.setHorizontalGroup(
            JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOwnOcean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(JpanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddShip))
                    .addGroup(JpanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddShip1))
                    .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelEnemyOcean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonSend))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        JpanelBackgroundLayout.setVerticalGroup(
            JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelBackgroundLayout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(JpanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpanelBackgroundLayout.createSequentialGroup()
                        .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelBackgroundLayout.createSequentialGroup()
                                .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelOwnOcean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelEnemyOcean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JpanelBackgroundLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSend)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jLabelPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAddShip1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddShip))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
        if(jTextAreaNewMessage.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El contenido del mensaje está vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        System.out.println("Ok client Two");
        // TODO: Check...
        //System.out.println(this.serviceChat.sendMessageClientOne(jTextAreaNewMessage.getText(), ""));
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jButtonAddShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddShipActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonAddShipActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelBackground;
    private javax.swing.JButton jButtonAddShip;
    private javax.swing.JButton jButtonAddShip1;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JPanel jPanelEnemyOcean;
    private javax.swing.JPanel jPanelOwnOcean;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaChat;
    private javax.swing.JTextArea jTextAreaNewMessage;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
